services:
  mariadb:
    image: mariadb:11
    container_name: travel_erp_mariadb
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: travel_erp
      MARIADB_USER: travel_erp
      MARIADB_PASSWORD: travel_erp
    ports:
      - "3306:3306"
    volumes:
      - travel_erp_mariadb:/var/lib/mysql

volumes:
  travel_erp_mariadb:
